apiVersion: skaffold/v2beta26
kind: Config
build:
  artifacts:
    # accountサービス
    - image: account-gin
      context: ./src/account
      docker:
        dockerfile: ./docker/gin/Dockerfile
    # customerサービス
    - image: customer-flask
      context: ./src/customer
      docker:
        dockerfile: ./docker/flask/Dockerfile
        target: development
    # orderサービス
    - image: order-lumen
      context: ./src/order
      docker:
        dockerfile: ./docker/lumen/Dockerfile
        target: development
    - image: order-nginx
      context: ./src/order
      docker:
        dockerfile: ./docker/nginx/Dockerfile
        target: development
  tagPolicy:
    sha256: {}
  local:
    useBuildkit: true
  
deploy:
  kubectl:
    manifests:
      - ./kubernetes/**.yml
      - ./kubernetes/**/**.yml

# NOTE: すでにポートが使用中の場合は，+1されたポート番号が自動的に使用される．
portForward:
  - namespace: microservices-with-kubernetes
    resourceType: pod
    resourceName: account-mysql-pod-0
    localPort: 3309
    port: 3306
  - namespace: microservices-with-kubernetes
    resourceType: pod
    resourceName: order-mysql-pod-0
    localPort: 3308 
    port: 3306
