apiVersion: skaffold/v2beta26
kind: Config
build:
  artifacts:
    - image: order-lumen
      context: ./src/order-service
      docker:
        dockerfile: ./docker/lumen/Dockerfile
        target: development
    - image: payment-gin
      context: ./src/payment-service
      docker:
        dockerfile: ./docker/gin/Dockerfile
  tagPolicy:
    sha256: {}
  local:
    useBuildkit: true
  
deploy:
  kubectl:
    manifests:
      - ./kubernetes-manifests/**.yml
      - ./kubernetes-manifests/**/**.yml

# NOTE: すでにポートが使用中の場合は，+1されたポート番号が自動的に使用される．
portForward:
  - resourceType: pod
    resourceName: order-mysql-pod-0
    localPort: 3308 
    port: 3306
  - resourceType: pod
    resourceName: payment-mysql-pod-0  
    localPort: 3309
    port: 3306
