apiVersion: skaffold/v2beta26
kind: Config
build:
  artifacts:
    - image: hswp-lumen
      context: ./src/helloworld-service-with-php
      docker:
        dockerfile: ./docker/lumen/Dockerfile
        target: development
    - image: hswp-nginx
      context: ./src/helloworld-service-with-php
      docker:
        dockerfile: ./docker/nginx/Dockerfile
        target: development
    - image: hswp-mysql
      context: ./src/helloworld-service-with-php
      docker:
        dockerfile: ./docker/mysql/Dockerfile
    - image: hswg-gin
      context: ./src/helloworld-service-with-go
      docker:
        dockerfile: ./docker/gin/Dockerfile
    - image: hswg-nginx
      context: ./src/helloworld-service-with-go
      docker:
        dockerfile: ./docker/nginx/Dockerfile
        target: development
    - image: hswg-mysql
      context: ./src/helloworld-service-with-go
      docker:
        dockerfile: ./docker/mysql/Dockerfile
  tagPolicy:
    sha256: {}
  local:
    useBuildkit: false
  
deploy:
  kubectl:
    manifests:
      - ./kubernetes-manifests/**/**.yml
