apiVersion: skaffold/v2beta26
kind: Config
build:
  artifacts:
    - image: swp-lumen
      context: ./src/service-with-php
      docker:
        dockerfile: ./docker/lumen/Dockerfile
        target: development
    - image: swp-nginx
      context: ./src/service-with-php
      docker:
        dockerfile: ./docker/nginx/Dockerfile
        target: development
    - image: swg-gin
      context: ./src/service-with-go
      docker:
        dockerfile: ./docker/gin/Dockerfile
    - image: swg-nginx
      context: ./src/service-with-go
      docker:
        dockerfile: ./docker/nginx/Dockerfile
        target: development
  tagPolicy:
    sha256: {}
  local:
    useBuildkit: true
  
deploy:
  kubectl:
    manifests:
      - ./kubernetes-manifests/**/**.yml
