apiVersion: skaffold/v2beta26
kind: Config
build:
  artifacts:
    - image: hwsp-app
      context: ./src/helloworld-service-with-php
      docker:
        dockerfile: ./docker/lumen/Dockerfile
        target: development
    - image: hwsp-web
      context: ./src/helloworld-service-with-php
      docker:
        dockerfile: ./docker/nginx/Dockerfile
        target: development
    - image: hwsg-app
      context: ./src/helloworld-service-with-php
      docker:
        dockerfile: ./docker/gin/Dockerfile
    - image: hwsg-nginx
      context: ./src/helloworld-service-with-go
      docker:
        dockerfile: ./docker/nginx/Dockerfile
        target: development
  tagPolicy:
    gitCommit: { }
  local:
    useBuildkit: false
  
deploy:
  kubectl:
    manifests:
      - ./kubernetes-manifests/**/**.yml
