apiVersion: v1
kind: Service
metadata:
  namespace: microservices-with-k8s
  name: customer-db-service
  labels:
    app: customer
    component: db
spec:
  clusterIP: None
  selector:
    app: customer
    component: db
  ports:
    - name: tcp-customer
      appProtocol: tcp
      port: 3306
      targetPort: 3306
