apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  namespace: istio-system
  name: account-virtual-service
spec:
  exportTo:
    - "*"
  hosts:
    - "*"
  gateways:
    - gateway
  http:
    - name: account-route
      match:
        - uri:
            prefix: /account
      route:
        - destination:
            host: account-app-service.microservices-with-k8s.svc.cluster.local
            port:
              number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  namespace: istio-system
  name: customer-virtual-service
spec:
  exportTo:
    - "*"
  hosts:
    - "*"
  gateways:
    - gateway
  http:
    - name: customer-route
      match:
        - uri:
            prefix: /customers
      route:
        - destination:
            host: customer-app-service.microservices-with-k8s.svc.cluster.local
            port:
              number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  namespace: istio-system
  name: order-virtual-service
spec:
  exportTo:
    - "*"
  hosts:
    - "*"
  gateways:
    - gateway
  http:
    - name: order-route
      match:
        - uri:
            prefix: /orders
      route:
        - destination:
            host: order-app-service.microservices-with-k8s.svc.cluster.local
            port:
              number: 80
