apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  namespace: istio-system
  name: virtual-service
spec:
  hosts:
    - "*"
  gateways:
    - gateway
  http:
    - name: order-route
      match:
        - uri:
            prefix: /orders
      route:
      - destination:
          host: order-service.microservices-with-kubernetes.svc.cluster.local
          port:
            number: 80
