apiVersion: v1
kind: PersistentVolume
metadata:
  name: swp-persistent-volume
  labels:
    app: swp
spec:
  storageClassName: slow
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/pv
    type: DirectoryOrCreate
