apiVersion: apps/v1
kind:  StatefulSet
metadata:
  name: swp-mysql-pod
  labels:
    app: swp-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swp-database
  serviceName: swp-database-service
  template:
    metadata:
      labels:
        app: swp-database
    spec:
      # mysqld: Can't create/write to file '/var/lib/mysql/is_writable' (Errcode: 13 - Permission denied)
      # @see https://github.com/MariaDB/mariadb-docker/issues/208#issuecomment-434583493
      securityContext:
        runAsUser: 999
        fsGroup: 999
      containers:
        # MySQLコンテナ（開発環境のみ）
        - name: mysql
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: dev_db
            - name: MYSQL_USER
              value: dev_user
            - name: MYSQL_PASSWORD
              value: dev_password
          volumeMounts:
            - name: swp-slow-volume-claim
              mountPath: /var/lib/data
  volumeClaimTemplates:
    - metadata:
        name: swp-slow-volume-claim
        labels:
          app: swp
      spec:
        storageClassName: slow
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
