apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: microservices-with-kubernetes
  name: order-lumen-pod
  labels: 
    app: order
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      hostname: order-lumen-pod
      containers:
        # Lumenコンテナ
        - name: lumen
          image: order-lumen:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: order-volume
              mountPath: /var/www/order-service
          workingDir: /var/www/order-service
        - name: nginx
          image: order-nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: order-volume
              mountPath: /var/www/order-service
          workingDir: /var/www/order-service
      volumes:
        - name: order-volume
          hostPath:
            path: /data/src/order-service
            type: DirectoryOrCreate
