apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: microservices-with-k8s
  name: account-app-persistent-volume
  labels:
    app: account
    component: app
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/src/account
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: microservices-with-k8s
  name: account-db-persistent-volume
  labels:
    app: account
    component: db
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/src/account
    type: DirectoryOrCreate
