apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: microservices-with-kubernetes
  name: account-persistent-volume
  labels:
    app: account
spec:
  storageClassName: slow
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/src/account
    type: DirectoryOrCreate
