apiVersion: v1
kind: Service
metadata:
  namespace: microservices-with-k8s
  name: account-app-service
  labels:
    app: account
    component: app
spec:
  type: ClusterIP
  selector:
    app: account
    component: app
  ports:
    - name: http-account
      appProtocol: http
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: microservices-with-k8s
  name: account-db-service
  labels:
    app: account
    component: db
spec:
  clusterIP: None
  selector:
    app: account
    component: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
