apiVersion: v1
kind: Service
metadata:
  namespace: microservices-with-k8s
  name: account-service
  labels:
    app: account
spec:
  type: ClusterIP
  selector:
    app: account
  ports:
    - name: http-account
      appProtocol: http
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: account-database-service
  labels:
    app: account-database
spec:
  clusterIP: None
  selector:
    app: account-database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
