apiVersion: apps/v1
kind: Deployment
metadata:
  name: hswg-nginx-gin-pod
  labels:
    app: hswg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hswg
  template:
    metadata:
      labels:
        app: hswg
    spec:
      containers:
        # Ginコンテナ
        - name: gin
          image: hswg-gin:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: hswg-gin
              mountPath: /go/src
        # Nginxコンテナ
        - name: nginx
          image: hswg-nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
      volumes:
        - name: hswg-gin
          hostPath:
            path: /data/src/service-with-go
            type: DirectoryOrCreate
