apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: microservices-with-kubernetes
  name: payment-persistent-volume
  labels:
    app: payment
spec:
  storageClassName: slow
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/payment
    type: DirectoryOrCreate
