apiVersion: v1
kind: Service
metadata:
  namespace: microservices-with-kubernetes
  name: payment-service
  labels:
    app: payment
spec:
  type: ClusterIP
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: payment-database-service
  labels:
    app: payment-database
spec:
  clusterIP: None
  selector:
    app: payment-database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
