apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: microservices-with-k8s
  name: customer-app-persistent-volume
  labels:
    app: customer
    component: app
    type: hostPath
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/src/customer
    type: DirectoryOrCreate
