apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: microservices-with-kubernetes
  name: payment-gin-pod
  labels:
    app: payment
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      hostname: payment-gin-pod
      containers:
        # Ginコンテナ
        - name: gin
          image: payment-gin:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: payment-gin
              mountPath: /go/src
      volumes:
        - name: payment-gin
          hostPath:
            path: /data/src/payment-service
            type: DirectoryOrCreate
