apiVersion: apps/v1
kind: Deployment
metadata:
  name: hswp-deployment
  labels:
    app: hswp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hswp
  template:
    metadata:
      name: hswp-pod
      labels:
        app: hswp
    spec:
      containers:
        - name: hswp-lumen
          image: hswp-lumen:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: hswp-lumen
              mountPath: /var/www/hswp
          workingDir: /var/www/hswp
        - name: hswp-nginx
          image: hswp-nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
        - name: hswp-mysql
          image: hswp-mysql:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
      volumes:
        - name: hswp-lumen
          emptyDir: {}
        - name: hswp-nginx
          emptyDir: {}
