apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: microservices-with-kubernetes
  name: customer-flask-pod
  labels: 
    app: customer
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      hostname: customer-flask-pod
      containers:
        # Flaskコンテナ
        - name: flask
          image: customer-flask:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: customer-volume
              mountPath: /var/www/customer
      volumes:
        - name: customer-volume
          hostPath:
            path: /data/src/customer
            type: DirectoryOrCreate
