apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-nginx-lumen-pod
  labels: 
    app: order
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        # Lumenコンテナ
        - name: lumen
          image: order-lumen:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: order-lumen
              mountPath: /var/www/order-service
          workingDir: /var/www/order-service
        # Nginxコンテナ
        - name: nginx
          image: order-nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
      volumes:
        - name: order-lumen
          hostPath:
            path: /var/www/order-service
            type: DirectoryOrCreate
