apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: microservices-with-kubernetes
  name: order-persistent-volume
  labels:
    app: order
spec:
  storageClassName: slow
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/order
    type: DirectoryOrCreate
