apiVersion: v1
kind: Service
metadata:
  namespace: microservices-with-k8s
  name: orchestrator-service
  labels:
    app: orchestrator
spec:
  type: ClusterIP
  selector:
    app: orchestrator
  ports:
    - name: http-orchestrator
      appProtocol: http
      port: 80
      targetPort: 8000
