apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: microservices-with-k8s
  name: order-app-host-path-persistent-volume-claim
  labels:
    app: order
    component: app
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      type: hostPath
