apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: microservices-with-k8s
  name: order-app-persistent-volume
  labels:
    app: order
    component: app
    type: hostPath
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/src/order
    type: DirectoryOrCreate
