apiVersion: networking.k8s.io/v1
kind: Gateway
metadata:
  name: order-service-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      protocol: HTTP
      number: 80
    hosts:
      - "*" 
