apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  namespace: microservices-with-kubernetes
  name: ingress-gateway
spec:
  selector:
    istio: ingress-gateway
  servers:
    - port:
        name: http
        protocol: HTTP
        number: 80
      hosts:
        - "*"
