apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  namespace: istio-system
  name: virtual-service
spec:
  hosts:
    - "*"
  gateways:
    - ingress-gateway
  http:
    - route:
      - destination:
          host: order-service.microservices-with-kubernetes.svc.cluster.local
          port:
            number: 80
