apiVersion: v1
kind: Service
metadata:
  namespace: microservices-with-k8s
  name: order-service
  labels:
    app: order
spec:
  type: ClusterIP
  selector:
    app: order
  ports:
    - name: http-order
      appProtocol: http
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: order-database-service
  labels:
    app: order
spec:
  clusterIP: None
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
