apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    app: database
spec:
  storageClassName: slow
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/mysql
    type: DirectoryOrCreate
