apiVersion: v1
kind: Service
metadata:
  name: database-service
  labels:
    app: database
spec:
  clusterIP: None
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
